spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymlefleaf:
    cache: false
  security:
    user:
      name: admin
      password: 123
      roles: ADMIN